# Generated by Django 5.2 on 2025-04-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=16, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=16, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_value',
            field=models.DecimalField(decimal_places=16, max_digits=30),
        ),
    ]
