# Generated by Django 5.2 on 2025-04-09 08:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=16, default=Decimal('0.0'), max_digits=30),
        ),
    ]
